"""empty message

Revision ID: 63ea946e1c1b
Revises: 0be04e7ed375
Create Date: 2022-10-13 21:25:18.152298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ea946e1c1b'
down_revision = '0be04e7ed375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('salt', sa.String(length=250), nullable=False))
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'salt')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
